apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-backup-config
  labels:
    app: redis-backup
data:
  REDIS_HOST: redis-master.default.svc.cluster.local
  REDIS_PORT: "6379"
  BACKUP_DIR: /backup
  BACKUP_RETENTION_DAYS: "7"
  REDIS_CONFIG: |
    # Advanced performance tuning
    maxmemory 6gb
    maxmemory-policy volatile-lfu
    maxmemory-samples 15
    
    # Enhanced I/O settings
    io-threads 8
    io-threads-do-reads yes
    dynamic-hz yes
    
    # Improved persistence techniques
    aof-use-rdb-preamble yes
    rdb-save-incremental-fsync yes
    
    # Memory optimization tuning
    active-defrag-ignore-bytes 100mb
    active-defrag-cycle-min 15
    jemalloc-bg-thread yes
    
    # Connection tuning parameters
    tcp-keepalive 45
    tcp-backlog 2048
    maxclients 15000
