apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-backup-config
  labels:
    app: redis-backup
data:
  REDIS_HOST: redis-master.default.svc.cluster.local
  REDIS_PORT: "6379"
  BACKUP_DIR: /backup
  BACKUP_RETENTION_DAYS: "7"
  REDIS_CONFIG: |
    # Memory management
    maxmemory 4gb
    maxmemory-policy volatile-ttl
    maxmemory-samples 20
    
    # Performance tuning
    io-threads 8
    io-threads-do-reads yes
    dynamic-hz yes
    
    # Enhanced security
    protected-mode yes
    rename-command FLUSHALL ""
    rename-command FLUSHDB ""
    rename-command CONFIG ""
    rename-command DEBUG ""
    
    # Persistence
    aof-use-rdb-preamble yes
    aof-timestamp-enabled yes
    rdb-save-incremental-fsync yes
    
    # Advanced optimizations
    active-defrag-max-scan-fields 2000
    active-expire-effort 10
    active-defrag-ignore-bytes 200mb
    jemalloc-bg-thread yes
    
    # Network
    tcp-keepalive 30
    tcp-backlog 1024
