version: '3.8'
services:
  discord-media-bot:
    container_name: discord-media-bot
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      # ...other necessary environment variables...
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 20s
      timeout: 5s
      retries: 3
    networks:
      - app-network
    restart: always
  redis:
    container_name: redis
    image: redis:7.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxclients 10000
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
    restart: always
  dashboard:
    container_name: dashboard
    build:
      context: ..
      dockerfile: Dockerfile
    command: python -m src.ui.dashboard
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always
  discord-media-selfbot:
    container_name: discord-media-selfbot
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9091:9090"  # different external port for selfbot
    environment:
      - STREAMING_BOT_TOKEN=your_streaming_selfbot_token
      - SERVICE_MODE=selfbot
      # ...other necessary environment variables...
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - app-network
    restart: always
volumes:
  redis-data:
    driver: local
networks:
  app-network:
    driver: bridge