version: '3.8'
services:
  discord-media-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    security_opt:
      - no-new-privileges:true
      - seccomp=default
    ports:
      - "127.0.0.1:9090:9090"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=info
      - NODE_ENV=development
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.1
      - MALLOC_ARENA_MAX=2
      - PYTHONMALLOC=malloc
      - GOMAXPROCS=2
      - DD_PROFILING_ENABLED=true
      - REDIS_POOL_SIZE=50
      - REDIS_MIN_IDLE=10
      - OTEL_BATCH_SPAN_PROCESSOR_EXPORT_TIMEOUT=30000
      - OTEL_BSP_MAX_QUEUE_SIZE=4096
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=512
      - REDIS_POOL_CONFIG={"maxsize":50,"minsize":10,"timeout":30}
      - NODE_OPTIONS=--max-old-space-size=1024 --gc-interval=100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    networks:
      app-network:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 1024
    security_opt:
      - no-new-privileges:true
    networks:
      app-network:
        ipv4_address: 172.28.0.3
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.name: app_net
      com.docker.network.driver.mtu: 1500