version: '3.8'
services:
  discord-media-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:9090"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=info
      - NODE_ENV=production
      - REDIS_POOL_SIZE=50
      - OTEL_BATCH_SPAN_PROCESSOR_EXPORT_TIMEOUT=30000
      - OTEL_BSP_MAX_QUEUE_SIZE=4096
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      app-network:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 1024
    security_opt:
      - no-new-privileges:true
    networks:
      app-network:
        ipv4_address: 172.28.0.3
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.name: app_net
      com.docker.network.driver.mtu: 1500